# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # kernel
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  hardware.enableAllFirmware = true;

  boot.initrd.luks.devices."enc-pv".device = "/dev/disk/by-uuid/78aa7e52-8da8-48aa-a7bf-2ae89d832e6b";

  
  # Enable sound.
  sound.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/15c6492f-b54d-41d5-8c3c-cfba7316083e";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D153-97CF";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6661b8c9-7e64-4073-8248-b5dff6825aa5"; }
    ];

  hardware = {

    #sound
    pulseaudio.package = pkgs.pulseaudioFull;
    pulseaudio.enable = true;

   #graphics
   opengl = {
     driSupport32Bit = true;
     enable = true;
     extraPackages = with pkgs; [
       vaapiIntel
       vaapiVdpau
       libvdpau-va-gl
       intel-media-driver
     ];
   };
  };

  nixpkgs.config.packageOverrides = pkgs: {
    vaapiIntel = pkgs.vaapiIntel.override { enableHybridCodec = true; };
  };

  services.xserver = {
    enable = true;
    videoDrivers = [ "intel" ];
  };

}
